[package]
name = "ishare"
version = "0.1.0"
authors = ["machengim <macheng83@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.5"
clap = "3.0.0-beta.2"
crossterm = "0.18"
dotenv = "0.15.0"
rand = "0.7.3"